config {
  type: "table",
  schema: "gold",
  description: "Ingredients dimension table"
}

SELECT
  FARM_FINGERPRINT("-999999") AS sk_ingredient,
  -999999 AS id_ingredient,
  'Unknown' AS name,
  'Unknown' AS unit,
  FALSE AS is_public

UNION ALL

SELECT
  FARM_FINGERPRINT(CONCAT('PUBLIC|', CAST(id_ingredient AS STRING))) AS sk_ingredient,
  id_ingredient,
  name,
  unit,
  TRUE AS is_public
FROM ${ref("stg_public_ingredient")}

UNION ALL

SELECT
  FARM_FINGERPRINT(CONCAT('PRIVATE|', CAST(id_ingredient AS STRING))) AS sk_ingredient,
  id_ingredient,
  name,
  unit,
  FALSE AS is_public
FROM ${ref("stg_private_ingredient")}
