config {
  type: "table",
  schema: "gold",
  description: "Payment methods dimension table",
  bigquery: {
    clusterBy: ["id_payment_method"]
  }
}

SELECT
  FARM_FINGERPRINT("-999999") AS sk_payment_method,
  -999999 AS id_payment_method,
  0 AS type_id,
  'Unknown' AS type,
  'Unknown' AS currency,
  'Unknown' AS card_brand,
  FALSE AS mobile,
  0 AS state_id,
  'Unknown' AS state

UNION ALL

SELECT
  FARM_FINGERPRINT(CAST(id_payment_method AS STRING)) AS sk_payment_method,
  id_payment_method,
  type AS type_id,
  CASE
    WHEN type = 1 THEN 'CARD_TOKEN'
    WHEN type = 2 THEN 'PAY_BY_LINK'
    ELSE 'UNKNOWN'
  END AS type,
  currency,
  card_brand,
  mobile,
  state AS state_id,
  CASE
    WHEN state = 0 THEN 'PRIMARY'
    WHEN state = 1 THEN 'ACTIVE'
    WHEN state = 2 THEN 'EXPIRED'
    WHEN state = 3 THEN 'ENABLED'
    WHEN state = 4 THEN 'DISABLED'
    WHEN state = 5 THEN 'TEMPORARY_DISABLED'
    WHEN state = 6 THEN 'WAITING_FOR_3DS2'
    WHEN state = 7 THEN 'WAITING_FOR_CVV'
    WHEN state = 8 THEN 'REJECTED'
    ELSE 'UNKNOWN'
  END AS state
FROM ${ref("stg_payment_method")}
