config {
  type: "view",
  schema: "silver",
  description: "Cleaned and standardized public ingredient data from catalog-db"
}

SELECT
  CAST(Id AS INT64) AS id_ingredient,
  CAST(Name AS STRING) AS name,
  CAST(Unit AS STRING) AS unit,
  CAST(Created AS TIMESTAMP) AS created_at,
  CAST(Updated AS TIMESTAMP) AS updated_at,
  CAST(UserId AS STRING) AS user_id
FROM ${ref("raw_catalog_PublicIngredient")}
