config {
  type: "table",
  schema: "gold",
  description: "Fact table for Delivery Items",
  bigquery: {
    partitionBy: "sk_date_delivery",
    clusterBy: ["sk_customer", "sk_product"]
  }
}

SELECT
  FARM_FINGERPRINT(COALESCE(CAST(di.id_delivery_item AS STRING), "-999999")) AS sk_delivery_item,
  
  COALESCE(di.id_delivery_item, -999999) AS id_delivery_item,
  COALESCE(d.id_customer_address, -999999) AS id_customer_address,
  COALESCE(d.id_delivery_man, -999999) AS id_delivery_man,
  COALESCE(di.id_product, -999999) AS id_product,
  COALESCE(di.id_delivery, -999999) AS id_delivery,
  COALESCE(d.id_site, -999999) AS id_site,
  COALESCE(ca.id_customer, -999999) AS id_customer,
  COALESCE(a.id_location, -999999) AS id_location,
  COALESCE(d.id_order, -999999) AS id_order,
  
  COALESCE(FARM_FINGERPRINT(CAST(a.id_location AS STRING)), FARM_FINGERPRINT("-999999")) AS sk_location,
  COALESCE(FARM_FINGERPRINT(CAST(ca.id_customer AS STRING)), FARM_FINGERPRINT("-999999")) AS sk_customer,
  COALESCE(FARM_FINGERPRINT(CAST(d.id_delivery_man AS STRING)), FARM_FINGERPRINT("-999999")) AS sk_delivery_man,
  COALESCE(FARM_FINGERPRINT(CAST(d.id_site AS STRING)), FARM_FINGERPRINT("-999999")) AS sk_site,
  COALESCE(FARM_FINGERPRINT(CAST(d.id_customer_address AS STRING)), FARM_FINGERPRINT("-999999")) AS sk_customer_address,
  COALESCE(FARM_FINGERPRINT(CAST(di.id_product AS STRING)), FARM_FINGERPRINT("-999999")) AS sk_product,
  COALESCE(CAST(a.delivery_date AS DATE), CAST("1970-01-01" AS DATE)) AS sk_date_delivery,
  COALESCE(CAST(di.created_at AS DATE), CAST("1970-01-01" AS DATE)) AS sk_date_delivery_created,
  COALESCE(CAST(di.modified_at AS DATE), CAST("1970-01-01" AS DATE)) AS sk_date_delivery_modified,
  
  COALESCE(di.planned_quantity, 0) AS planned_quantity,
  COALESCE(di.packed_quantity, 0) AS packed_quantity,
  COALESCE(di.product_price, 0) AS product_price,
  
  COALESCE(di.planned_quantity, 0) * COALESCE(di.product_price, 0) AS planned_amount,
  COALESCE(di.packed_quantity, 0) * COALESCE(di.product_price, 0) AS packed_amount,
  
  COALESCE(d.state_id, -999999) AS delivery_state_id,
  COALESCE(d.state, 'UNKNOWN') AS delivery_state,
  COALESCE(di.state_id, -999999) AS delivery_item_state_id,
  COALESCE(di.state, 'UNKNOWN') AS delivery_item_state,
  
  COALESCE(di.packed_quantity < di.planned_quantity, FALSE) AS is_shortage

FROM ${ref("stg_delivery_items")} di
LEFT JOIN ${ref("stg_deliveries")} d 
  ON di.id_delivery = d.id_delivery AND di.id_delivery != 0
LEFT JOIN ${ref("stg_area_of_delivery_for_date")} a 
  ON d.id_area_of_delivery_for_date = a.id_area_of_delivery_for_date AND d.id_area_of_delivery_for_date != 0
LEFT JOIN ${ref("stg_customer_address")} ca 
  ON d.id_customer_address = ca.id_customer_address AND d.id_customer_address != 0
