config {
  type: "table",
  schema: "gold",
  description: "Bridge table linking Products (dim_product) and Ingredients (dim_ingredient)"
}

SELECT
  FARM_FINGERPRINT(CONCAT('PUBLIC|', CAST(id_product_ingredient AS STRING))) AS sk_product_ingredient,
  id_product_ingredient,
  id_product,
  id_ingredient,
  value,
  TRUE AS is_public
FROM ${ref("stg_product_public_ingredient")}

UNION ALL

SELECT
  FARM_FINGERPRINT(CONCAT('PRIVATE|', CAST(id_product_ingredient AS STRING))) AS sk_product_ingredient,
  id_product_ingredient,
  id_product,
  id_ingredient,
  value,
  FALSE AS is_public
FROM ${ref("stg_product_private_ingredient")}
